version: "3.8"
services:
  rabbitmq3:
    container_name: "orderContainer"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rystemasqar
      - RABBITMQ_DEFAULT_PASS=0055
    ports:
      - '5672:5672'
      - '15672:15672'